<?php
define('MAINTENANCE_ON', false);
define('STIPEND_INTERVAL_SECONDS', 43200);

$GLOBALS['mime_types'] = [
    'image' => [
        'image/jpeg',
        'image/png',
        'image/webp'
    ],
    'audio' => ['audio/mpeg',
        'audio/x-wav',
        'audio/ogg',
        'audio/wav',
        'audio/opus'],
    'mesh' => ['text/plain'],
    'hat' => ['text/plain'],
    'head' => ['text/plain'],
    'raw' => ['application/octet-stream', 'text/plain'],
    'face' => [
        'image/jpeg',
        'image/png',
        'image/webp'
    ]
];

$GLOBALS['color_schemes'] = [
    [
        'name' => 'Vanilla',
        'primary' => '#000000',
        'secondary' => '#ffffff',
    ],
    [
        'name' => 'Solarized',
        'primary' => '#002b36',
        'secondary' => '#fdf6e3',
    ],
    [
        'name' => 'gruvbox',
        'primary' => '#1d2021',
        'secondary' => '#fbf1c7',
    ],
    [
        'name' => 'brat',
        'primary' => '#000000',
        'secondary' => '#85c700',
    ],
];

$GLOBALS['sidebars_list'] = [
    [
        'name' => 'Day',
        'url' => 'sidebarday.png'
    ],
    [
        'name' => 'Afternoon',
        'url' => 'sidebarafn.png'
    ],
    [
        'name' => 'Night',
        'url' => 'sidebarnit.png'
    ],
    [
        'name' => "I can't see the end of the horizon...",
        'url' => 'popipo.gif'
    ],
    [
        'name' => 'No more horses.',
        'url' => 'horses.png'
    ],
    [
        'name' => '67',
        'url' => '67.gif'
    ],
    [
        'name' => 'Keep calm and Gangnam Style',
        'url' => 'keepcalmandgangnamstyle.jpg'
    ],
    [
        'name' => 'DAMN!!!',
        'url' => 'pukeko.jpg'
    ],
    [
        'name' => 'Shrek',
        'url' => 'shrek.gif'
    ],
    [
        'name' => 'LOL! LSDBLOX!',
        'url' => 'LOL.gif'
    ],
];

$GLOBALS['fonts_list'] = [
    [
        'name' => 'Liberation Sans',
        'font_family' => 'libsans',
        'url' => '/assets/fonts/LiberationSans-Regular.ttf'
    ],
    [
        'name' => 'FreeSans',
        'font_family' => 'freesans',
        'url' => '/assets/fonts/FreeSans.ttf'
    ],
    [
        'name' => 'Dinkie Bitmap',
        'font_family' => 'dink',
        'url' => '/assets/fonts/dink.ttf'
    ],
    [
        'name' => 'PULSE',
        'font_family' => 'pulse',
        'url' => '/assets/fonts/pulse.ttf'
    ],
    [
        'name' => 'Comic Sans MS',
        'font_family' => 'comicsans',
        'url' => '/assets/fonts/COMIC.TTF'
    ],
    [
        'name' => 'Roboto',
        'font_family' => 'roboto',
        'url' => '/assets/fonts/Roboto-Regular.ttf'
    ],
    [
        'name' => 'Ubuntu',
        'font_family' => 'ubuntu',
        'url' => '/assets/fonts/Ubuntu-Regular.ttf'
    ],
    [
        'name' => 'IBM PC',
        'font_family' => 'ibm_pc',
        'url' => '/assets/fonts/ibm.woff2'
    ],
    [
        'name' => 'Arial',
        'font_family' => 'msarial',
        'url' => '/assets/fonts/arial.ttf'
    ],
    [
        'name' => 'Impact',
        'font_family' => 'msimpact',
        'url' => '/assets/fonts/Impacted.ttf'
    ],
    [
        'name' => 'Special Elite',
        'font_family' => 'special_elity',
        'url' => '/assets/fonts/SpecialElite.ttf'
    ],
    [
        'name' => 'Papryus (Freaky font)',
        'font_family' => 'papyrus_freak',
        'url' => '/assets/fonts/papyrus.ttf'
    ],
];

$GLOBALS['asset_types'] = [
    'image' => [1, 4, 5, 6, 7],
    'audio' => [2],
    'hat' => [8],
    'head' => [9],
];

$GLOBALS['brickcolor'] = ['111111' => 1003, '575857' => 148, 'A1A5A2' => 2, 'CDCDCD' => 1002, 'ECECEC' => 40, 'F8F8F8' => 1001, 'EDEAEA' => 348, 'E9DADA' => 349, 'FFC9C9' => 1025, 'FF9494' => 337, '965555' => 344,
    'A34B4B' => 1007, '883E3E' => 350, '562424' => 339, 'FF5959' => 331, '750000' => 332, '970000' => 327, 'FF0000' => 1004, '966766' => 360, 'BE6862' => 338, '957977' => 153,
    'CD544B' => 41, 'C4281C' => 21, 'DA867A' => 101, 'D9856C' => 47, '97695B' => 176, 'EEC4B6' => 100, 'D36F4C' => 123, '904C2A' => 216,
    '8F4C2A' => 345, 'CF6024' => 193, 'D5733D' => 133, '694028' => 192, 'CC8E69' => 18, '564236' => 361, 'AF9483' => 359, 'AE7A59' => 128, 'A05F35' => 38, '6C584B' => 355,
    '7C5C46' => 217, '5A4C42' => 364, 'E09864' => 137, 'EAB892' => 125, '624732' => 25, 'DA8541' => 106, 'CB8442' => 12, 'B48455' => 178, '6A3909' => 365,
    'AA5500' => 1014, 'FFCC99' => 1030, '756C62' => 168, 'EBB87F' => 225, 'E29B40' => 105, 'E7AC58' => 121, 'F3CF9B' => 36, 'DCBC81' => 127, '7E683F' => 362,
    'BC9B5D' => 351, 'A0844F' => 356, 'D3BE96' => 346, 'C7AC78' => 352, 'F0D5A0' => 224, 'D7A94B' => 180, 'E8AB2D' => 191, '685C43' => 108, '958A73' => 138, 'B08E44' => 209,
    'FFAF00' => 1017, 'FFB000' => 1005, 'EFB838' => 333, 'D7C59A' => 5, 'CABFA3' => 353, 'F1E7C7' => 340,
    'F8D96D' => 334, 'F5CD30' => 24, 'F9D62E' => 190, 'FDEA8D' => 226, 'F9E999' => 3, 'FEF3BB' => 341, 'E2DCBC' => 347, 'FFF67B' => 157, 'F8F184' => 49,
    'F7F18D' => 44, 'C1BE42' => 1008, 'FFFFCC' => 1029, 'FFFF00' => 1009, 'D8DD56' => 134, 'C7D23C' => 115, '828A5D' => 200, 'D9E4A7' => 120, 'A4BD47' => 119,
    '7F8E64' => 1022, 'B9C4B1' => 319, 'A8BD99' => 324, 'A1C48C' => 29, '3A7D15' => 1021, '7C9C6B' => 317, '94BE81' => 323, 'C2DAB8' => 6, '2C651D' => 304,
    '5B9A4C' => 310, 'B1E5A6' => 328, '8AAB85' => 318, '1F801D' => 313, 'CCFFCC' => 1028, '4B974B' => 37, '00FF00' => 1020, '348E40' => 309, '506D54' => 301,
    '84B68D' => 48, '27462D' => 141, '709578' => 210, '287F47' => 28, '789082' => 151, '9FF3E9' => 1027, '12EED4' => 1018, 'B7D7D5' => 118, '00FFFF' => 1019,
    '008F9C' => 107, '55A5AF' => 116, '04AFEC' => 1013, '0989CF' => 315, '7DBBDD' => 232, '80BBDC' => 11, 'C1DFF0' => 42,
    '98C2DB' => 329, 'B4D2E4' => 45, '0D69AC' => 23, '1B2A35' => 26, 'AFDDFF' => 1024, '7BB6E8' => 43, '9FC3E9' => 212, '203A56' => 140, 'CFE2F7' => 143,
    '335882' => 306, '6E99CA' => 102, '527CAE' => 305, 'C7D4E4' => 336, '74869D' => 135, '9FADC0' => 314, '7988A1' => 145, '4667A4' => 195, '23478B' => 196, '2154B9' => 1012,
    '002060' => 1011, '6C81B7' => 213, '161D32' => 149, '435493' => 110, '6874AC' => 112, '102ADC' => 307,
    '0010B0' => 303, 'A7A9CE' => 220, 'A5A5CB' => 126, '0000FF' => 1010, 'B1A7FF' => 1026, '342B75' => 268, '6B629B' => 219,
    '6225D1' => 1031, '3D1585' => 308, 'B480FF' => 1006, '8C5B9F' => 1023, '6B327C' => 104, '96709F' => 218, '7B2F7B' => 322, '592259' => 312, '7B007B' => 316,
    'AA00AA' => 1015, '8E4285' => 198, 'A75E9B' => 321, 'FF00BF' => 1032, '923978' => 124, 'FF66CC' => 1016, 'D490BD' => 343, 'FF98DC' => 330, 'E0B2D0' => 342,
    'C470A0' => 22, 'CD6298' => 221, 'E1A4C2' => 158, 'E4ADC8' => 222, 'E5ADC8' => 113, 'E8BAC8' => 9, 'DC9095' => 223];

$GLOBALS['countries_list_iso_codes'] = [
    'AF' => 'Afghanistan',
    'AX' => 'Åland Islands',
    'AL' => 'Albania',
    'DZ' => 'Algeria',
    'AS' => 'American Samoa',
    'AD' => 'Andorra',
    'AO' => 'Angola',
    'AI' => 'Anguilla',
    'AQ' => 'Antarctica',
    'AG' => 'Antigua & Barbuda',
    'AR' => 'Argentina',
    'AM' => 'Armenia',
    'AW' => 'Aruba',
    'AU' => 'Australia',
    'AT' => 'Austria',
    'AZ' => 'Azerbaijan',
    'BS' => 'Bahamas',
    'BH' => 'Bahrain',
    'BD' => 'Bangladesh',
    'BB' => 'Barbados',
    'BY' => 'Belarus',
    'BE' => 'Belgium',
    'BZ' => 'Belize',
    'BJ' => 'Benin',
    'BM' => 'Bermuda',
    'BT' => 'Bhutan',
    'BO' => 'Bolivia',
    'BA' => 'Bosnia & Herzegovina',
    'BW' => 'Botswana',
    'BV' => 'Bouvet Island',
    'BR' => 'Brazil',
    'IO' => 'British Indian Ocean Territory',
    'VG' => 'British Virgin Islands',
    'BN' => 'Brunei',
    'BG' => 'Bulgaria',
    'BF' => 'Burkina Faso',
    'BI' => 'Burundi',
    'KH' => 'Cambodia',
    'CM' => 'Cameroon',
    'CA' => 'Canada',
    'CV' => 'Cape Verde',
    'BQ' => 'Caribbean Netherlands',
    'KY' => 'Cayman Islands',
    'CF' => 'Central African Republic',
    'TD' => 'Chad',
    'CL' => 'Chile',
    'CN' => 'China',
    'CX' => 'Christmas Island',
    'CC' => 'Cocos (Keeling) Islands',
    'CO' => 'Colombia',
    'KM' => 'Comoros',
    'CG' => 'Congo - Brazzaville',
    'CD' => 'Congo - Kinshasa',
    'CK' => 'Cook Islands',
    'CR' => 'Costa Rica',
    'CI' => 'Côte d’Ivoire',
    'HR' => 'Croatia',
    'CU' => 'Cuba',
    'CW' => 'Curaçao',
    'CY' => 'Cyprus',
    'CZ' => 'Czechia',
    'DK' => 'Denmark',
    'DJ' => 'Djibouti',
    'DM' => 'Dominica',
    'DO' => 'Dominican Republic',
    'EC' => 'Ecuador',
    'EG' => 'Egypt',
    'SV' => 'El Salvador',
    'GQ' => 'Equatorial Guinea',
    'ER' => 'Eritrea',
    'EE' => 'Estonia',
    'SZ' => 'Eswatini',
    'ET' => 'Ethiopia',
    'FK' => 'Falkland Islands',
    'FO' => 'Faroe Islands',
    'FJ' => 'Fiji',
    'FI' => 'Finland',
    'FR' => 'France',
    'GF' => 'French Guiana',
    'PF' => 'French Polynesia',
    'TF' => 'French Southern Territories',
    'GA' => 'Gabon',
    'GM' => 'Gambia',
    'GE' => 'Georgia',
    'DE' => 'Germany',
    'GH' => 'Ghana',
    'GI' => 'Gibraltar',
    'GR' => 'Greece',
    'GL' => 'Greenland',
    'GD' => 'Grenada',
    'GP' => 'Guadeloupe',
    'GU' => 'Guam',
    'GT' => 'Guatemala',
    'GG' => 'Guernsey',
    'GN' => 'Guinea',
    'GW' => 'Guinea-Bissau',
    'GY' => 'Guyana',
    'HT' => 'Haiti',
    'HM' => 'Heard & McDonald Islands',
    'HN' => 'Honduras',
    'HK' => 'Hong Kong SAR China',
    'HU' => 'Hungary',
    'IS' => 'Iceland',
    'IN' => 'India',
    'ID' => 'Indonesia',
    'IR' => 'Iran',
    'IQ' => 'Iraq',
    'IE' => 'Ireland',
    'IM' => 'Isle of Man',
    'IL' => 'Israel',
    'IT' => 'Italy',
    'JM' => 'Jamaica',
    'JP' => 'Japan',
    'JE' => 'Jersey',
    'JO' => 'Jordan',
    'KZ' => 'Kazakhstan',
    'KE' => 'Kenya',
    'KI' => 'Kiribati',
    'KW' => 'Kuwait',
    'KG' => 'Kyrgyzstan',
    'LA' => 'Laos',
    'LV' => 'Latvia',
    'LB' => 'Lebanon',
    'LS' => 'Lesotho',
    'LR' => 'Liberia',
    'LY' => 'Libya',
    'LI' => 'Liechtenstein',
    'LT' => 'Lithuania',
    'LU' => 'Luxembourg',
    'MO' => 'Macao SAR China',
    'MG' => 'Madagascar',
    'MW' => 'Malawi',
    'MY' => 'Malaysia',
    'MV' => 'Maldives',
    'ML' => 'Mali',
    'MT' => 'Malta',
    'MH' => 'Marshall Islands',
    'MQ' => 'Martinique',
    'MR' => 'Mauritania',
    'MU' => 'Mauritius',
    'YT' => 'Mayotte',
    'MX' => 'Mexico',
    'FM' => 'Micronesia',
    'MD' => 'Moldova',
    'MC' => 'Monaco',
    'MN' => 'Mongolia',
    'ME' => 'Montenegro',
    'MS' => 'Montserrat',
    'MA' => 'Morocco',
    'MZ' => 'Mozambique',
    'MM' => 'Myanmar (Burma)',
    'NA' => 'Namibia',
    'NR' => 'Nauru',
    'NP' => 'Nepal',
    'NL' => 'Netherlands',
    'NC' => 'New Caledonia',
    'NZ' => 'New Zealand',
    'NI' => 'Nicaragua',
    'NE' => 'Niger',
    'NG' => 'Nigeria',
    'NU' => 'Niue',
    'NF' => 'Norfolk Island',
    'KP' => 'North Korea',
    'MK' => 'North Macedonia',
    'MP' => 'Northern Mariana Islands',
    'NO' => 'Norway',
    'OM' => 'Oman',
    'PK' => 'Pakistan',
    'PW' => 'Palau',
    'PS' => 'Palestinian Territories',
    'PA' => 'Panama',
    'PG' => 'Papua New Guinea',
    'PY' => 'Paraguay',
    'PE' => 'Peru',
    'PH' => 'Philippines',
    'PN' => 'Pitcairn Islands',
    'PL' => 'Poland',
    'PT' => 'Portugal',
    'PR' => 'Puerto Rico',
    'QA' => 'Qatar',
    'RE' => 'Réunion',
    'RO' => 'Romania',
    'RU' => 'Russia',
    'RW' => 'Rwanda',
    'WS' => 'Samoa',
    'SM' => 'San Marino',
    'ST' => 'São Tomé & Príncipe',
    'SA' => 'Saudi Arabia',
    'SN' => 'Senegal',
    'RS' => 'Serbia',
    'SC' => 'Seychelles',
    'SL' => 'Sierra Leone',
    'SG' => 'Singapore',
    'SX' => 'Sint Maarten',
    'SK' => 'Slovakia',
    'SI' => 'Slovenia',
    'SB' => 'Solomon Islands',
    'SO' => 'Somalia',
    'ZA' => 'South Africa',
    'GS' => 'South Georgia & South Sandwich Islands',
    'KR' => 'South Korea',
    'SS' => 'South Sudan',
    'ES' => 'Spain',
    'LK' => 'Sri Lanka',
    'BL' => 'St. Barthélemy',
    'SH' => 'St. Helena',
    'KN' => 'St. Kitts & Nevis',
    'LC' => 'St. Lucia',
    'MF' => 'St. Martin',
    'PM' => 'St. Pierre & Miquelon',
    'VC' => 'St. Vincent & Grenadines',
    'SD' => 'Sudan',
    'SR' => 'Suriname',
    'SJ' => 'Svalbard & Jan Mayen',
    'SE' => 'Sweden',
    'CH' => 'Switzerland',
    'SY' => 'Syria',
    'TW' => 'Taiwan',
    'TJ' => 'Tajikistan',
    'TZ' => 'Tanzania',
    'TH' => 'Thailand',
    'TL' => 'Timor-Leste',
    'TG' => 'Togo',
    'TK' => 'Tokelau',
    'TO' => 'Tonga',
    'TT' => 'Trinidad & Tobago',
    'TN' => 'Tunisia',
    'TR' => 'Turkey',
    'TM' => 'Turkmenistan',
    'TC' => 'Turks & Caicos Islands',
    'TV' => 'Tuvalu',
    'UM' => 'U.S. Outlying Islands',
    'VI' => 'U.S. Virgin Islands',
    'UG' => 'Uganda',
    'UA' => 'Ukraine',
    'AE' => 'United Arab Emirates',
    'GB' => 'United Kingdom',
    'US' => 'United States',
    'UY' => 'Uruguay',
    'UZ' => 'Uzbekistan',
    'VU' => 'Vanuatu',
    'VA' => 'Vatican City',
    'VE' => 'Venezuela',
    'VN' => 'Vietnam',
    'WF' => 'Wallis & Futuna',
    'EH' => 'Western Sahara',
    'YE' => 'Yemen',
    'ZM' => 'Zambia',
    'ZW' => 'Zimbabwe',
];

function country2flag(string $countryCode): string  // https://gist.github.com/IonBazan/b0d6165b2dfa1afc6329ea885e1feeb5
{
    return (string) preg_replace_callback(
        '/./',
        static fn(array $letter) => mb_chr(ord($letter[0]) % 32 + 0x1F1E5),
        $countryCode
    );
}
